version: '2'
services:
  app:
    build: .
    command:
        [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
    volumes:
      - .:/app
      - ~/.aws:/root/.aws
    volumes_from:
      - bundle
    ports:
      - "3000:3000"
    links:
      - db
  bundle:
    image: busybox
    volumes:
      - /bundle
  db:
    image: tutum/dynamodb
  aws:
    image: cgswong/aws
    volumes:
      - ~/.aws:/root/.aws
      - .:/work
    working_dir: /work
    environment:
      AWS_REGION: ap-northeast-1
